channels:
  - adl/label/dev
  - conda-forge/label/cf202003
  - defaults
dependencies:
  - spot=2.8.7.dev.108
  - graphviz
  - r-irkernel
  - r-ggplot2
  - r-tidyverse
  - bfurneaux::r-tikzdevice
  - pandas
  - scipy

